updated stuff

diff --git a/usr/local/bin/grimm b/usr/local/bin/grimm
--- a/usr/local/bin/grimm
+++ b/usr/local/bin/grimm
@@ -1,32 +1,40 @@
 #!/bin/bash
 # Author: Luke Kreft
 
-# a wrapper for error messages
-crit() { echo "Error: $*"; exit;}
+# these will likely be set one day by an installation script
 
-# loading necessary files
-[ -e config.sh ] && source config.sh || crit "could not load a config file"
-[ -e functions.sh ] && source functions.sh || crit "could not find functions file"
+# primary locations
+log_dir=${prefix}/var/log/grimm
+lib_dir=${prefix}/usr/local/lib/grimm
+data_dir=${prefix}/var/lib/grimm
+
+# derivative locations
+mod_dir=${lib_dir}/modules
+db_dir=${data_dir}/dbs
+
+# strings, I guess
+start_time=( "$(date +%F_%H.%M.%S)" "$(date)" "$(date +%s)" )
+
+# a wrapper for error messages
+crit() { echo "Error: $*" >&2; exit;}
 
 # safety checks
 [ -e /etc/debian_version ] || [ -e /etc/redhat-release ] || crit "script only supports cent and debian at this time"
 (( $( id -u ) )) && crit "must be run as root"
+[ -e /etc/grimm ] && source /etc/grimm || crit "could not load a config file"
 
-# getting set up
-[ -d "${dir}" ] || mkdir -p "${dir}"
-[ -d "${dir}" ] || crit "could not create working directory: ${dir}"
+# set up the installer
 [ -e /etc/debian_version ] && install() { apt-get install -y "$*" 2>"${log_dir}/install.log";}
 [ -e /etc/redhat-release ] && install() { yum install -y "$*" 2>"${log_dir}/install.log";}
+# null out the list of dependencies - modules will regenerate this
+echo > ${data_dir}/bash_dependencies.txt
 
 # loading the modules
-[ -d "${mod_dir}" ] && find "${mod_dir}" -maxdepth 2 -type f -name main.sh -exec source "{}" \;
+[ -d "${mod_dir}" ] && find "${mod_dir}" -maxdepth 2 -type f -name functions.sh -exec source "{}" \;
 
 # installing dependencies
-if [ -e "${dir}"/dependencies.txt ]
-then
-  for program in $(sed 's|#.*||' "${dir}"/dependencies.txt)
-  do
-    [ $(command -v $program) ] || install $program
-    [ $(command -v $program) ] || crit "could not install needed program: $program"
-  done
-fi
+for program in $(sed 's|#.*||' "${data_dir}"/bash_dependencies.txt)
+do
+  [ $(command -v $program) ] || install $program
+  [ $(command -v $program) ] || crit "could not install needed program: $program"
+done
